### ISSUE TITLE
Conda package for wxpython 4.2.1

### ISSUE THREAD

**Issue by serhiy-yevtushenko** [conda-forge/wxpython-feedstock#103]
### Comment:

Hi, the wxpython 4.2.1 is now available (https://pypi.org/project/wxPython/4.2.1/#files).

Could you please clarify, whether there are any plans to add conda package for this release of wxpython and if yes, what is the estimated timelines?

Many thanks in advance

**Comment by pauldmccarthy** [comment]
wxpython 4.2.1 should be available within the next few hours (see #104)
