### ISSUE TITLE
Development version is installed from main channel

### ISSUE THREAD

**Issue by moorepants** [conda-forge/wxpython-feedstock#12]
If I `conda install -c conda-forge wxpython` I get:

```
wxpython                  4.0.0rc1.dev3440+0f9b36e          py35_0    conda-forge
```

This is a development version it seems. I'm not sure what the conventions are but it would be preferable if this was contained in an rc release channel so it isn't picked up on a standard install call.

**Comment by Korijn** [comment]
Feel free to open a PR to correct the issue.

**Comment by bilderbuchi** [comment]
Just a drive-by FYI, 4.0.0 final has been released: https://groups.google.com/forum/#!topic/wxpython-dev/ZQ2ZE4hzRcc

**Comment by ChrisBarker-NOAA** [comment]
4.0.1 now in master.

This issue could/should be closed

**Comment by ocefpaf** [comment]
At the time we did not have any stable release. Now we are packaging the latest stable releases and the dev ones were moved to the dev label.
