### ISSUE TITLE
Version 4.0.0 is out!

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [conda-forge/wxpython-feedstock#13]
Let's get it into conda-forge!

And can we PLEASE figure out how to get an OS_X build up?

I understand that CI limits are killing us, so two options that I see:

1) one of us builds it locally and hand-uploads to Anaconda.org. Last I tried, I couldn't get the build to work on my machine -- maybe I'll try again.

2) we re-package the wheels that Robin is posting to PyPi -- this seems to work fine for me, but it's not ideal -- however, not having anything isn't ideal either, and practicality beats purity and all that.

**Comment by ChrisBarker-NOAA** [comment]
Here's the announcement:

https://groups.google.com/forum/#!topic/wxpython-dev/ZQ2ZE4hzRcc

**Comment by Korijn** [comment]
I'm out, sorry, it's too big of a time investment for me. Good luck.

**Comment by ChrisBarker-NOAA** [comment]
OK, 4.0.1 now merged in master, and sorta working:

#15, #16
