### ISSUE TITLE
Windows build failing on py27 and 36, passing on 35.

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [conda-forge/wxpython-feedstock#16]
Windows builds are failing on Appveyor:

https://ci.appveyor.com/project/conda-forge/wxpython-feedstock/build/1.0.65

But they fail well before it gets to the actual build -- issue with the Appveyor setup and the compiler version maybe ?!?!?

**Comment by ocefpaf** [comment]
Closing this as stale. Please re-open if this is still relevant.
