### ISSUE TITLE
Build version 4.0.4?

### ISSUE THREAD

**Issue by hoechenberger** [conda-forge/wxpython-feedstock#30]
Hello, would you consider publishing a package for `wxpython` 4.0.4? 4.0.3 seems to have some nasty bugs that cause problems for some of my apps, and packages of previous releases are not available for Python 3.7, which I am using. I would very much appreciate your effort!

**Comment by ocefpaf** [comment]
Done in #26

**Comment by hoechenberger** [comment]
Awesome, thank you!
