### ISSUE TITLE
Missing linux dependency in feedstock?

### ISSUE THREAD

**Issue by pauldmccarthy** [conda-forge/wxpython-feedstock#31]
Howdy,

It looks like a dependency is missing from the wxpython linux feedstock. When running in the `conda-forge` linux build container (`docker run -it condaforge/linux-anvil-comp7 bash`), the following commands:

```
conda create -y -p testenv python=3.6
conda activate `pwd`/testenv
conda install -y -c conda-forge wxpython
python -c "import wx"
```

produce this error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conda/testenv/lib/python3.6/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/home/conda/testenv/lib/python3.6/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: libXxf86vm.so.1: cannot open shared object file: No such file or directory
```
 I think this has not been seen before because `libXxf86vm` is being implicitly installed due to `gtk2-devel` being listed in `yum_requirements.txt`. 

I've tried and failed to resolve the issue by running `conda install -c conda-forge libXxf86vm-cos6-x86_64`. Any ideas?

**Comment by ocefpaf** [comment]
The docker container does not provide the `X` libraries. They are expected to be present in the end user system.
