### ISSUE TITLE
Use SPDX Syntax to define about.license

### ISSUE THREAD

**Issue by timsnyder** [conda-forge/wxpython-feedstock#45]
# Issue:

[Recipe linter complains about wxpython not following SPDX](https://github.com/conda-forge/wxpython-feedstock/pull/44#issuecomment-602636011)

# Background:

[wxpython currently uses `wxWindows Library v3.1` ](https://github.com/conda-forge/wxpython-feedstock/blob/7810b864cb22dfd3cb8cab6bf528792aeef74d32/recipe/meta.yaml#L106) as the text in `about.license`.

If I understand correctly, looking at the SPDX documentation:
* https://spdx.org/licenses/
* https://spdx.org/licenses/WxWindows-exception-3.1.html

And the wxpython library licensing docs at:
* https://wxpython.org/pages/license/

# Proposed Fix

- [x] `about.license` needs to be changed to `LGPL-2.0-or-later WITH WxWindows-exception-3.1` 
- [x]  we also need to make sure that the LGPL-2.0 license text is also included in the package
   - the LICENSE.txt in wxpython source tarball contains the full license txt including LGPLv2

**Comment by isuruf** [comment]
`LGPL-2.0-or-later WITH WxWindows-exception-3.1` looks correct.
