### ISSUE TITLE
Depend on wxwidgets (from conda-forge)

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/wxpython-feedstock#49]
Now that [`wxwidgets`]( https://github.com/conda-forge/wxwidgets-feedstock ) is packaged in `conda-forge`. It would be good to add it as a dependency.

cc @conda-forge/wxwidgets (for vis)

**Comment by hmaarrfk** [comment]
We still don't have a osx build. Help would be appreciated there.

**Comment by jakirkham** [comment]
Yeah tracking a macOS build as issue ( https://github.com/conda-forge/wxwidgets-feedstock/issues/1 ).

In any event, we can probably still use it on Linux and Windows until macOS is added.
