### ISSUE TITLE
Add GTK dependency

### ISSUE THREAD

**Issue by Korijn** [conda-forge/wxpython-feedstock#5]
This would drastically reduce system dependencies on linux. @ocefpaf

**Comment by Korijn** [comment]
See #3 for related discussion and builds.

**Comment by jakirkham** [comment]
Opened issue ( https://github.com/conda-forge/staged-recipes/issues/3914 ) to discuss adding `gtk` to `conda-forge`. A rough attempt at doing this can be seen in PR ( https://github.com/conda-forge/staged-recipes/pull/3920 ).

**Comment by Korijn** [comment]
As detailed in https://github.com/conda-forge/wxpython-feedstock/pull/10 wxPython started using GTK3 by default since v4.0.0b2, which apparently is not just unavailable on conda-forge, but even on centOS which is what linux-anvil is based on. Jeez!

**Comment by ocefpaf** [comment]
This was done some time ago and we forgot to close the issue.
