### ISSUE TITLE
Port to Gtk 3?

### ISSUE THREAD

**Issue by alexdewar** [conda-forge/wxpython-feedstock#82]
### Comment:

It seems that someone attempted this with PR #51 a couple of years ago, but lost interest.

It would be good to port this to Gtk 3 as Gtk 2 is basically dead at this point (Gtk 4 has already been released) and it looks ugly as sin on most Linux desktops.

**Comment by hmaarrfk** [comment]
May i suggest trying to use the wxWidgets package i built up. https://github.com/conda-forge/wxwidgets-feedstock

it might avoid alot of the difficult building.

However, I still don't have osx packages there, so it might be a hybrid approach :/

**Comment by JaRoSchm** [comment]
In the meantime it looks like that osx packages were added in https://github.com/conda-forge/wxwidgets-feedstock. Is there any way to move forward with this issue now?

**Comment by hmaarrfk** [comment]
i personally lost interest in wxPython so I won't be able to help do the heavy lifting. Do feel free to attempt a port with a PR. Others can always help review.

**Comment by JaRoSchm** [comment]
Thanks for your answer. Sadly this doesn‘t look like a good first issue for me as I have no experience with packaging at all. Maybe one of the maintainers can help here @constantinpape @ocefpaf @timsnyder?

**Comment by JaRoSchm** [comment]
That's completely understandable. I'm only bound to it for an internal tool where the effort to port it to some other framework is not worth it. Then I will probably keep pip-installing it.

**Comment by pauldmccarthy** [comment]
Done in #122
